#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Kari Vierimaa, Kempele, Finland
#
# Ancillary repository file (not Covered Source). RTL is under Apache-2.0; see NOTICE.

"""Regenerate poc.f (root), Bender.yml, and poc.core from verilator file lists."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

FRAGMENTS = [
    "verilator/files/common.f",
    "verilator/files/arith.f",
    "verilator/files/mem.f",
    "verilator/files/sync.f",
    "verilator/files/fifo.f",
    "verilator/files/dstruct.f",
    "verilator/files/bus.f",
    "verilator/files/bus_axi_pkg.f",
    "verilator/files/bus_axi4.f",
    "verilator/files/bus_axi4lite.f",
    "verilator/files/bus_axi4lite_demux.f",
    "verilator/files/bus_axi4stream.f",
]


def rtl_files() -> list[str]:
    files: list[str] = []
    seen: set[str] = set()
    for rel in FRAGMENTS:
        path = ROOT / rel
        if not path.is_file():
            continue
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line.startswith("src/") and line.endswith(".sv") and line not in seen:
                seen.add(line)
                files.append(line)
    return files


def sim_files() -> list[str]:
    return sorted(p.relative_to(ROOT).as_posix() for p in (ROOT / "sim").rglob("*.sv"))


def write_root_poc_f(rtl: list[str]) -> None:
    header = """// SPDX-FileCopyrightText: 2026 Kari Vierimaa, Kempele, Finland
//
// Ancillary repository file (not Covered Source). RTL is under Apache-2.0; see NOTICE.
//
// Complete PoC_sv RTL file list. Verilator regression uses verilator/poc.f and
// verilator/files/sim_*.f; regenerated by tools/gen_packaging.py.

+incdir+src
"""
    (ROOT / "poc_packaging.f").write_text(header + "\n".join(rtl) + "\n", encoding="utf-8", newline="\n")


def write_bender(rtl: list[str]) -> None:
    lines = [
        "# SPDX-FileCopyrightText: 2026 Kari Vierimaa, Kempele, Finland",
        "# Regenerated by tools/gen_packaging.py.",
        "",
        "package:",
        "  name: poc-sv",
        "  authors:",
        '    - "Kari Vierimaa"',
        "  version: 0.1.3-review",
        "  description: SystemVerilog port of VHDL PoC (AXI first delivery)",
        "",
        "dependencies: {}",
        "",
        "export_include_dirs:",
        "  - src",
        "",
        "sources:",
    ]
    lines.extend(f"  - {path}" for path in rtl)
    (ROOT / "Bender.yml").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def write_core(rtl: list[str], sim: list[str]) -> None:
    lines = [
        "CAPI=2:",
        "",
        "# SPDX-FileCopyrightText: 2026 Kari Vierimaa, Kempele, Finland",
        "# Regenerated by tools/gen_packaging.py.",
        "",
        "name: kavierim:poc:sv:0.1.3-review",
        "description: PoC_sv Verilator-oriented RTL (AXI closure)",
        "",
        "filesets:",
        "  rtl:",
        "    files:",
    ]
    lines.extend(f"      - {path}" for path in rtl)
    lines.extend(
        [
            "    file_type: systemVerilogSource",
            "  sim:",
            "    files:",
        ]
    )
    lines.extend(f"      - {path}" for path in sim)
    lines.extend(
        [
            "    file_type: systemVerilogSource",
            "",
            "targets:",
            "  default:",
            "    filesets:",
            "      - rtl",
            "",
        ]
    )
    (ROOT / "poc.core").write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> None:
    rtl = rtl_files()
    sim = sim_files()
    write_root_poc_f(rtl)
    write_bender(rtl)
    write_core(rtl, sim)
    print(f"Wrote poc_packaging.f ({len(rtl)} RTL), Bender.yml, poc.core ({len(sim)} sim)")


if __name__ == "__main__":
    main()
